---
- hosts: all
  become: yes
  gather_facts: yes

  tasks:

    - name: Create /etc/docker conf directory
      file: path=/etc/docker state=directory

    - name: Install required package
      package:
        name: yum-utils
        state: present

    - name: Add Docker GPG key
      rpm_key:
        key: https://download.docker.com/linux/centos/gpg
        state: present

    - name: Add Docker repository
      get_url:
        url: "https://download.docker.com/linux/centos/docker-ce.repo"
        dest: '/etc/yum.repos.d/docker-ce.repo'
        owner: root
        group: root
        mode: 0644

    - name: Configure Docker Edge repo
      ini_file:
        dest: '/etc/yum.repos.d/docker-ce.repo'
        section: 'docker-ce-edge'
        option: enabled
        value: '0'

    - name: Install Docker
      package: 
        name: docker-ce 
        state: present

    - name: adding existing user 'vagrant' to group docker
      user:
        name: 'vagrant'
        groups: docker
        append: yes

    - name: Install Docker Compose (if configured)
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: "/usr/local/bin/docker-compose"
        mode: 0755

    - name: Ensure Docker is started and enabled at boot
      service:
        name: docker
        state: started
        enabled: yes

  handlers:
    - name: restart docker
      service: name=docker state=restarted

- hosts: all
  become: yes
  tasks:
    - name: Inject file docker-compose.yml in /tmp
      copy:
        src: docker-compose.yml
        dest: /tmp/docker-compose.yml
